# Generated by Django 6.0.1 on 2026-01-31 08:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=10)),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('province', models.CharField(choices=[('HNI', 'Hà Nội'), ('HCM', 'TP. Hồ Chí Minh'), ('DNG', 'Đà Nẵng')], default='HCM', max_length=3)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(default=10.8231, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(default=106.6297, verbose_name='Kinh độ')),
                ('music_playlist', models.TextField(blank=True, help_text='Mỗi bài hát 1 dòng')),
                ('hobbies', models.TextField(blank=True, help_text='Các sở thích cách nhau dấu phẩy')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('cover_photo', models.ImageField(blank=True, default='covers/default.jpg', upload_to='covers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
