# Generated by Django 6.0.1 on 2026-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(choices=[('HNI', 'Thành phố Hà Nội'), ('HPH', 'Thành phố Hải Phòng'), ('TQU', 'Tỉnh Tuyên Quang'), ('LCA', 'Tỉnh Lào Cai'), ('TNG', 'Tỉnh Thái Nguyên'), ('PTH', 'Tỉnh Phú Thọ'), ('BNI', 'Tỉnh Bắc Ninh'), ('HYE', 'Tỉnh Hưng Yên'), ('NBI', 'Tỉnh Ninh Bình'), ('QNI', 'Tỉnh Quảng Ninh'), ('LSO', 'Tỉnh Lạng Sơn'), ('CBA', 'Tỉnh Cao Bằng'), ('LCH', 'Tỉnh Lai Châu'), ('DBI', 'Tỉnh Điện Biên'), ('SLA', 'Tỉnh Sơn La'), ('THA', 'Tỉnh Thanh Hoá'), ('NAN', 'Tỉnh Nghệ An'), ('HTI', 'Tỉnh Hà Tĩnh'), ('HUE', 'Thành phố Huế'), ('QTR', 'Tỉnh Quảng Trị'), ('DNG', 'Thành phố Đà Nẵng'), ('QNG', 'Tỉnh Quảng Ngãi'), ('GLA', 'Tỉnh Gia Lai'), ('KHO', 'Tỉnh Khánh Hoà'), ('DLA', 'Tỉnh Đắk Lắk'), ('LDO', 'Tỉnh Lâm Đồng'), ('HCM', 'Thành phố Hồ Chí Minh'), ('DNI', 'Tỉnh Đồng Nai'), ('TNI', 'Tỉnh Tây Ninh'), ('CTO', 'Thành phố Cần Thơ'), ('VLG', 'Tỉnh Vĩnh Long'), ('DTH', 'Tỉnh Đồng Tháp'), ('AGI', 'Tỉnh An Giang'), ('CMU', 'Tỉnh Cà Mau')], default='HCM', max_length=10),
        ),
    ]
