# Generated by Django 6.0.1 on 2026-02-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0003_alter_userprofile_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Giới thiệu/Status'),
        ),
    ]
