# Generated by Django 6.0.1 on 2026-03-05 23:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_alter_userprofile_address_alter_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dating_with',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dating_app.userprofile', verbose_name='Đang hẹn hò với'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='dating_app.userprofile', verbose_name='Danh sách bạn bè'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('Độc thân', 'Độc thân vui tính'), ('Đang tìm hiểu', 'Đang tìm hiểu'), ('Đang hẹn hò', 'Đang hẹn hò (Hoa đã có chủ)'), ('Đã kết hôn', 'Đã kết hôn')], default='Độc thân', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=1, verbose_name='Giới thiệu/Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='covers/default.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, default=1, help_text='Các sở thích cách nhau dấu phẩy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(default=10.8231, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(default=106.6297, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='music_playlist',
            field=models.TextField(blank=True, default=1, help_text='Mỗi bài hát 1 dòng'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
