# Generated by Django 6.0.1 on 2026-03-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0007_datingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
