# Generated by Django 6.0.1 on 2026-04-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
